{{ config(materialized='table') }}
SELECT 
      A.AGENT_CODE,
      AGENT_NAME,
      A.WORKING_AREA, 
      B.OUTSTANDING_AMT, 
      B.CUST_CITY, 
      A.COMMISSION, 
      C.ORD_DATE
FROM MY_SCHEMA.AGENTS A
INNER JOIN  MY_SCHEMA.CUSTOMER B 
ON B.AGENT_CODE =A.AGENT_CODE
LEFT JOIN MY_SCHEMA.ORDERS C 
ON B.CUST_CODE = C.CUST_CODE
ORDER BY ORD_DATE


